# Generated by Django 5.2 on 2025-04-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='surname',
        ),
    ]
