# Generated by Django 5.2.1 on 2025-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='advantages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Переваги'),
        ),
        migrations.AddField(
            model_name='review',
            name='disadvantages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Недоліки'),
        ),
    ]
