# Generated by Django 5.2.1 on 2025-05-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Товар в кошику', 'verbose_name_plural': 'Товари в кошику'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Елемент замовлення', 'verbose_name_plural': 'Елементи замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
    ]
