# Generated by Django 5.2.1 on 2025-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_review_rating_review_advantages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='review',
            name='disadvantages',
        ),
    ]
