# Generated by Django 5.2.1 on 2025-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Ця міграція позначає існуючі таблиці як керовані цим додатком
        # Реальні таблиці вже існують і створені shop.migrations
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        )
    ]
