# Generated by Django 5.2.1 on 2025-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Відсоток знижки (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Чи товар у знижці'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оригінальна ціна (без знижок)', max_digits=10, null=True),
        ),
    ]
